### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by mindninjaX** [mindninjaX/Power-Tools#1]

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by mindninjaX** [comment]
Hi @aditya28sarin! Thank you so much for your interest in the issue. However, it would not be possible to create a README at this point of time due to lack of context. However, once we have progressed further, I will inform you and then you can go ahead creating a README for the project. Have a wonderful day ⚡
